### ISSUE TITLE
Empty value for MultipleChoiceField does not return any result.

### ISSUE THREAD

**Issue by xordoquy** [alex/django-filter#145]
When using a filter with a MultipleChoiceField even if required is False you won't get any result if left empty.

For example, I've been filtering names as a non required MultipleChoiceField. When I query page_list?name= I get no results while I'd expect an unfiltered list.

The issue has been narrowed to the filterset's associated form not being valid. The reason why it's not valid is that "name=" translates into data=[u''] which isn't a valid choice in my case. What should be given to the field is data=[]:

```
(Pdb) response.context_data['filter']._form.fields['name'].clean([u''])
*** ValidationError: [u'Select a valid choice.  is not one of the available choices.']
(Pdb) response.context_data['filter']._form.fields['bug_status'].clean([])
[]
```

**Comment by carltongibson** [comment]
This is also related to the #36, #45, #134 cluster.

**Comment by carltongibson** [comment]
OK. This is a doozy. 

If I set up a test like this: 

```
        class TestFilterSet(FilterSet):
            title = MultipleChoiceFilter(choices = [('a','a'), ('b','b'), ('c','c')])

            class Meta:
                model = Book
                fields = ['title',]
```

This is passes:

```
        f = TestFilterSet({'title':''})
        self.assertTrue(f.form.is_valid())
```

And this fails:

```
        f = TestFilterSet(QueryDict('title='))
        self.assertTrue(f.form.is_valid())
```

That's explicable, since if I'm expecting a list from a QueryDict I'll ask for one:

```
from django.http import QueryDict
q = QueryDict('title=')
q.getlist("title")
[u'']
```

...and sure enough that happens in [`SelectMultiple.value_from_datadict`](https://github.com/django/django/blob/master/django/forms/widgets.py#L607)

So the answer here is going to be implement a custom widget if you're likely to have this problem. 

Can we do better than that?
