### ISSUE TITLE
Dynamic lookup types

### ISSUE THREAD

**Issue by jpadilla** [alex/django-filter#220]
It'd be useful to allow client to specify the lookup_type for the field. Example: `?qty=1&qty_loookup_type=gte`

Ref: https://twitter.com/jpadilla_/status/583326079114461184

I could probably tackle this with a bit of guidance.

Update: Ideally this would render a form with a field for `foo` and a choice field for `foo_lookup_type`.

**Comment by carltongibson** [comment]
I was going to write, "There's no reason why this couldn't be supported...". 

I was then looking up [MultiValueField](https://docs.djangoproject.com/en/1.7/ref/forms/fields/#multivaluefield) and thinking it needs to be done with this and making sure the selected lookup type is valid. (If the form is not valid an empty QuerySet is returned — which is a fair behaviour here.) 

I then cracked open `fields.py` and saw [this](https://github.com/alex/django-filter/blob/develop/django_filters/fields.py#L27) added in 4eb281c8bdba4b99f6b3dcde4c7442ca4cc58731.

The docs are a bit skimpy — __really__ top of the things I need to do here — but what happens if you just supply an iterable to the `lookup_type` parameter (as discussed [here](https://django-filter.readthedocs.org/en/latest/ref/filters.html#lookup-type)?

**Comment by jpadilla** [comment]
@carltongibson hmmm that does seem to work. Shouldn't we be seeing the exact same behavior when doing this:

```python
class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product
        fields = {'price': ['lt', 'gt']}
```
which results in:

```html
<tr><th><label for="id_quantity__lt">Quantity:</label></th><td><input id="id_quantity__lt" name="quantity__lt" step="any" type="number" /></td></tr>
<tr><th><label for="id_quantity__gt">Quantity:</label></th><td><input id="id_quantity__gt" name="quantity__gt" step="any" type="number" /></td></tr>
```
and this:

```python
class ProductFilter(django_filters.FilterSet):
    price = django_filters.NumberFilter(lookup_type=['lt', 'gt'])
    class Meta:
        model = Product
        fields = ['price']
```

which results in:

```html
<tr><th><label for="id_quantity_0">Quantity:</label></th><td><input id="id_quantity_0" name="quantity_0" step="any" type="number" /><select id="id_quantity_1" name="quantity_1">
<option value="gt">gt</option>
<option value="lt">lt</option>
</select></td></tr>
```

**Comment by carltongibson** [comment]
That's a nice example. 

My first pass at the story goes like this: 

* the _One True Way_ to define a `FilterSet` is to do it explicitly, defining each filter as per your second `price` example; 
* the `fields` shortcut is a convenience for auto generating filters; 
* the dictionary syntax there (allowing multiple filters per field) is an extra convenience added onto that; 
* I'm not sure about making that any more complicated in order to switch between multiple filters vs dynamic lookups — it strikes me the syntactic gain over just defining the filters explicitly is limited. 

I'm happy to see any of that questioned — but I'm wary of adding too much here.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
