### ISSUE TITLE
Show all results but filtered with different style

### ISSUE THREAD

**Issue by Summer88** [alex/django-filter#260]
```
class Panel(models.Model):
   current_num = models.BigIntegerField() 
   tot_num = models.BigIntegerField()
   pt_code = models.TextField()

my filter:

def filter_category(queryset, value):
    qs = queryset.values('filterby')
    return queryset **and qs with custom property for template**

class ArchivFilter(django_filters.FilterSet):
     checkme= django_filters.BooleanFilter(action=filter_category)
```

Would it be possible  or it is already possible to add in the action *filter_category*  something like a special tag that allow, only for this view, that i.e. you can  show the the qs values with a different background-color?

**Comment by carltongibson** [comment]
Hey @Summer88 — Please use the [Mailing List](https://groups.google.com/forum/#!forum/django-filter) for usage questions. 

(Before cross posting there see if you can clarify what you're trying to do, as I have to say I don't understand the question. Styling is a CSS issue, rather than a Django one I'd think... You'd need to explain at length, on the mailing list.)

Thanks.
