### ISSUE TITLE
'RawQuerySet' object has no attribute 'all'

### ISSUE THREAD

**Issue by loict1** [alex/django-filter#271]
I'm trying to use a raw query but it throws me an error.

Here's the view code :

  data = RFQLine.objects.raw(
    '''select * from rfq_line a inner join 
        (select min(quantity) as min_q, item_id, rfq_id from rfq_line group by RFQ_ID, ITEM_ID) b 
            on a.QUANTITY = b.min_q and a.item_id = b.ITEM_ID and a.RFQ_ID = b.RFQ_ID 
            order by id;'''
            )
    f = RFQLineFilter(request.GET, queryset=data)

    return render(request, 'RFQ_list.html', {'data':f})

And the error : 'RawQuerySet' object has no attribute 'all'

Thanks

**Comment by loict1** [comment]
Nevermind I just created a view in the db.

**Comment by avanibhatnagar** [comment]
I'm having the same issue!

**Comment by rpkilby** [comment]
This isn't really a django-filter issue. `RawQuerySet`s allow you execute raw sql, but it's not possible to combine raw calls with regular ORM calls (`filter()`, `order_by()`, etc..). Since the purpose of django-filter is to validate and construct those ORM calls, `RawQuerySet` is just incompatible.
