### ISSUE TITLE
'field': ['isnull'] not working with django-filter 0.10.0 / Django 1.8 / DRF 3.1.2

### ISSUE THREAD

**Issue by elnygren** [alex/django-filter#273]
I am trying to set up a `field__isnull=True/False` filter but I'm can't get it to work with django-filter 0.10.0 / Django 1.8 / DRF 3.1.2.

Code that is _not_ working:
```
class MyFilter(django_filters.FilterSet):
    class Meta:
        model = MyModel
        fields = {
            'field': ['isnull'],
        }
```

`GET /api/my_model/?field__isnull=True` -> returns an empty array, no SQL is being ran according to Django's shell.

Code that did work:

```
class MyFilter(django_filters.FilterSet):
    field__isnull = django_filters.BooleanFilter(action=lambda q, v: q.filter(field__isnull=v))
    class Meta:
        model = MyModel
        fields = {
        ...some other field declarations
        }
```

`GET /api/my_model/?field__isnull=True` does what it is supposed to, SQL looks OK.

EDIT: the field I'm working with is a MySQL DateTimeField that is usually `null` but sometimes has a DateTime.

**Comment by carltongibson** [comment]
What's the problem here—that the dictionary syntax isn't getting the result you're after? Can you put together a test case showing this?

**Comment by elnygren** [comment]
The problem is that when declaring isnull filter with the dict syntax:

```
fields = {
            'field': ['isnull'],
        }
```

a request like `GET /api/my_model/?field__isnull=True` gets an empty array as response and Django does not even perform an SQL query (I log all SQL queries to console from Django)

**Comment by carltongibson** [comment]
Paging @eosrei — no worries if you're busy, but any chance you could put your head to this for a diagnosis? (Thanks!)

**Comment by eosrei** [comment]
@carltongibson Got it. I may be able to look at it next week.

**Comment by carltongibson** [comment]
@eosrei Awesome! Thanks!

**Comment by lingxiaoyang** [comment]
:+1:

**Comment by skolsuper** [comment]
I am having similar problem I think. djangorestframework==3.2.4, django-filter==0.11.0, Django==1.8.4, with the following code:

```
class AnglerFilter(TFFilterSet):

    user = django_filters.BooleanFilter(lookup_type='isnull', exclude=True)

    class Meta:
        model = Angler
        fields = ['user']
```

user is a OneToOneField on the angler model.  Angler.objects.filter(user__isnull=True) works, but this test fails:

```
def test_filter_by_user(self):
        other_angler = Angler.objects.first()
        self.assertIsNone(other_angler.user)
        test_user = UserFactory()
        AnglerFactory(user=test_user)
        self.assertIsNotNone(test_user.angler_profile)

        response = self.client.get(reverse('angler-list'))
        results = response.data['results']
        self.assertEqual(len(results), 5)
        angler_ids = map(itemgetter('id'), results)
        self.assertIn(test_user.angler_profile.id, angler_ids)

        response = self.client.get(reverse('angler-list') + '?user=True')
        results = response.data['results']
        self.assertEqual(len(results), 1)  # <-- fail here
```

**Comment by nitinbhojwani** [comment]
Seems, it's still not fixed. Is any body taking care of this issue?

**Comment by carltongibson** [comment]
Not yet. Pull requests welcome!

**Comment by adamcharnock** [comment]
@skolsuper I think your issue (which I suspect is the same issue I was having) was fixed in c9eacb2ef3439e77624aed0b524bb69b9d0aa3a6.

I can also reproduce the problem where the dictionary syntax does not work.

**Comment by adamcharnock** [comment]
I've just taken a look into this and it seems (to me) the problem lies in the `FILTER_FOR_DBFIELD_DEFAULTS` mechanism which provides a lookup between model fields and various `Filter` classes.

The assumption is that if one is dealing with a foreign key, then you'll want to use `ModelChoiceFilter` (i.e. one will specify an existing model ID), *regardless of what one is doing with that field*.

However, in our case we are doing an `isnull` `lookup_type`, therefore we are filtering on a boolean rather than a model ID.

A solution to this would therefore be to take account of *both* the field type *and* the `lookup_type` when determining the model field to use. For example:

* If `lookup_type` in (`isnull`, `range`, `hour`, `minute`, `second`, `day`, `month`, `year`, `week_day`) then let that determine the field type (`BooleanField`, something sensible for range, and int fields for the rest)
* Otherwise, defer to `FILTER_FOR_DBFIELD_DEFAULTS`

Alternative solutions:

1. Just code in a special case for `isnull`
2. Don't bother. Just put a note in the docs saying "if you want to do this then don't use the dictionary syntax" :)

**Comment by carltongibson** [comment]
I'm inclined towards 2. 

Basically, explicit declaration should be considered the _one right way_ — everything else is a convenience (and I'm not keen on adding more code to work around edge cases in the conveniences).

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. I'm happy to receive a PR on the Docs explaining the limitation. 

(I'd also happily review something that addressed the issue cleanly)
