### ISSUE TITLE
Forms widgets in template

### ISSUE THREAD

**Issue by bretanac93** [alex/django-filter#323]
Hi, I'm building an ecommerce web app, and I'm using this package for filtering the data, but I got the following problem, I have in my project several BooleanFields, in the admin these fields are shown as checkboxes, but when I configure the django-filter package, these same fields are shown in the form as selector with three posible values (Unknown, Yes, No), but I need to replace these selector and put checkboxes instead, is there any kind of problem or something?, is working justs like when you put in the model NullBooleanField, but I don't want that, I just want to show to my users the checkboxes, thanks and kind regards

**Comment by rpkilby** [comment]
Hi @bretanac93 - I believe this is the expected behavior. Filters are usually optional, which is why both `NullBooleanField`s and `BooleanField`s are [mapped](https://github.com/alex/django-filter/blob/0.12.0/django_filters/filterset.py#L200-L202) to `BooleanFilter` (which uses `NullBooleanField` under the hood). Django by default uses a choice widget for booleans, so this is why you're seeing the generated output. That said, there are a couple of places you can modify the behavior.

Filters accept a widget argument, so you if you're manually instantiating filters...
```py
class MyFilter(FilterSet):
    my_boolean_field = filters.BooleanFilter(name='my_boolean_field', widget=forms.CheckboxInput)

    class Meta:
        model = MyModel
```

However, if you're using the meta class to declare fields, then you can override the behavior with [`filter_overrides`](https://django-filter.readthedocs.org/en/latest/usage.html#the-filter).

```py
class MyFilter(FilterSet):
    filter_overrides = {
        models.BooleanField: {
            'filter_class': filters.BooleanFilter,
            'extra': lambda f: {
                widget: forms.CheckboxInput
            },
        }
    }
    class Meta:
        model = MyModel
        fields = ['my_boolean_field']
```

**Comment by rpkilby** [comment]
@userino666. Django's `CheckboxInput` [returns `True`/`False`](https://github.com/django/django/blob/2.0.4/django/forms/widgets.py#L526-L536) values. If you want it to return `True`/`None`, you'll have to override the widget with your custom behavior.
